---
# tasks file for transactional_update

- name: "Run transactional update"
  command: "/usr/sbin/transactional-update"
  register: transactional_update
  changed_when:
    - '"zypper: nothing to update" not in transactional_update.stdout'
  notify:
    - "Reboot"
    - "Wait for the machine(s) to be ready again"

- name: 'transactional-updates: force reboot at this point to not loose changes'
  meta: flush_handlers
